baseURL = "https://persycchiotto.netlify.com/"
languageCode = "it-IT"
defaultContentLanguage = "it"

title = "Appunti di Persycchiotto"
theme = "hugo-theme-learn"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"
  math = true
  disableSearch = true
