baseURL = "http://www.persycchiotto.it/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Appunti di Persycchiotto"
theme = "hugo-theme-learn"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"
