---
title: "1. Introduzione alle Scienze della Terra"
draft: false
weight: 1
---

= Le Scienze della Terra
:toc: preamble
:toc-title: Contenuti:
:table-caption: Tabella
:figure-caption: Immagine

_L’espressione “scienze della Terra” è stata coniata di recente: fino a qualche anno fa, le varie discipline scientifiche che rientrano sotto questa comune denominazione (tra cui astronomia, geografia fisica, geologia) venivano definite “scienze naturali” (tale espressione comprendeva anche la biologia, la zoologia, la botanica ecc., discipline che studiano gli esseri viventi)._

== Che cosa sono le scienze della Terra
*Le scienze della Terra raggruppano* oggi una serie di *settori disciplinari rivolti allo studio di corpi materiali non viventi* (masse d’aria, corpi idrici, ammassi rocciosi) e *all’osservazione di fenomeni naturali* (meteorologici, sismici, vulcanici, geomorfologici, idrologici, oceanografici ecc.).

La nascita, abbastanza recente, di una sensibilità, oltre che di un interesse “ecologico” generalizzato, ha introdotto nell’ambito delle scienze della Terra indirizzi di studio incentrati sull’ambiente, inteso come sede delle risorse dell’uomo, ma anche come “bene collettivo” soggetto a vari “impatti” negativi: inquinamento, erosione, desertificazione, rischi sismici ecc. In definitiva, le scienze della Terra assommano tutte le discipline teoriche “classiche” e quelle
sviluppatesi con funzione applicativa, cioè in grado di fornire strumenti utili per le attività umane (per esempio, la geologia ambientale o la geologia applicata), che si dedicano allo studio del nostro pianeta.

Se all’inizio la ricerca si è dedicata allo studio del particolare, oggi si tende a ricostruire i “*sistemi ambientali*”, unendo e correlando le varie informazioni. Attualmente si tende a considerare e a interpretare i fenomeni di varia natura che interessano la superficie terrestre in una prospettiva unitaria, che guarda alla Terra, o meglio al “*sistema Terra*”, come a un insieme di “sistemi ambientali” interagenti, al cui studio concorrono le conoscenze provenienti dai differenti ambiti di ricerca, secondo un’impostazione interdisciplinare.

Secondo il modello più generale, il sistema Terra viene distinto in alcuni grandi sistemi ambientali o “domini”: la geosfera, l’idrosfera e l’atmosfera.

La *geosfera* è costituita dalla Terra solida, a partire dal suo nucleo fino alla crosta terrestre; l’**idrosfera** è il dominio dell’acqua, sia quella presente sulla superficie (oceani, mari, laghi, fiumi, ghiacciai), sia quella ipogea (falde acquifere), sia il vapore acqueo atmosferico; l’**atmosfera** è l’involucro gassoso che circonda il pianeta.
Geosfera, idrosfera e atmosfera interagiscono attraverso scambi di energia e di materia.

Il quadro, tuttavia, si completa considerando un quarto sistema ambientale: quello dove ha sede la vita, denominato **biosfera**, o **ecosfera**, che permea gli altri tre componenti del sistema Terra e interagisce con essi. Lo spazio nel quale si svolge la vita interessa la parte superficiale della geosfera (**litosfera**) emergente dalle acque (terre emerse), l’idrosfera e lo strato più basso dell’atmosfera (**troposfera**).

---

.Tabella delle discipline a carattere scientifico (1)
[cols="1,2",width="100%"]
|===
|Discipline a carattere scientifico |Oggetto di studio

|cristallografia    |forma e struttura dei cristalli
|geochimica         |Scomposizione chimica dei corpi geologici terrestri
|geofisica          |fisica terrestre, campi di forze associati alla Terra (magnetico, gravitazionale)
|geografia fisica   |fenomeni naturali dell’atmosfera e dell’idrosfera; fenomeni legati ai climi; loro rapporti ed effetti sulla superficie terrestre
|geologia           |comprende i campi della stratigrafia, della tettonica della sedimentologia e della geocronologia
|geologia storica   |storia degli eventi geologici
|geomorfologia      |forme del paesaggio, loro genesi ed evoluzione
|geopedologia       |suoli e loro genesi
|glaciologia        |fenomeni naturali in cui sono coinvolti i ghiacciai
|idrografia         |distribuzione delle acque superficiali
|limnologia         |fenomeni lacustri
|mineralogia        |costituzione fisica e chimica dei minerali
|oceanografia       |fenomeni che hanno luogo negli oceani e nei mari
|paleontologia      |fossili di animali e di vegetali
|petrografia e petrologia |genesi e caratteristiche delle rocce ignee, |stratigrafia |rapporti cronologici tra gli eventi sedimentari
|sismologia         |terremoti
|tettonica          |strutture acquisite dalle masse rocciose in seguito a fenomeni
deformativi
|vulcanologia       |fenomeni vulcanici
|===

---

.Tabella delle discipline a carattere scientifico (2)
[cols="1,2", width="100%"]
|===
|Discipline a carattere applicativo |Oggetto di studio

|geologia agraria           |geopedologia applicata; tecnica delle irrigazioni
|geologia ambientale        |aspetti di carattere geologico della realtà ambientale
|geologia degli idrocarburi |giacimenti petroliferi
|geologia delle costruzioni |condizioni di realizzazione delle opere ingegneristiche
|geomorfologia applicata    |difesa dei versanti e delle coste; difesa dai rischi naturali
|geotecnica                 |proprietà fisiche delle rocce
|geotermia                  |fluidi caldi provenienti dal sottosuolo
|giacimentologia            |giacimenti minerari e cave
|idrogeologia               |ricerche d’acqua (potabile, minerale, termale)
|meccanica delle rocce      |proprietà fisiche delle masse rocciose
|meteorologia               |fenomeni atmosferici e previsioni del tempo
|petrografia applicata      |proprietà delle pietre da costruzione e dei materiali naturali utilizzati nell’edilizia e nel restauro di opere d’arte
|===
